[MenuTexts]
sMenuConfiguration = Configuration
; Tabs
sTabEconomy = Economy and Gameplay Settings
sTabColors = Colors and Display
sTabLabels = Label Naming

; Tab 1
sLiveEnabled = Trading Mode Active in Live Session
sBootEnabled = Trading Mode Active in Boot and New Game
sToggleKey = Trading Toggle Key
sWealthKey = Wealth Check Key
sItemValueMode = Item Value Mode
sSpendingOrderMode = Spending Priority
sItemValueMode0 = Currency (Buy Price)
sItemValueMode1 = Barter (Sell Price)
sItemValueMode2 = Fixed (Base Value)
sSpendingPriority0 = Lowest Value/Weight
sSpendingPriority1 = Highest Value/Weight
sSpendingPriority2 = Heaviest
sSpendingPriority3 = Lightest
sSpendingPriority4 = Cheapest
sSpendingPriority5 = Most Expensive
sSpendingPriority6 = None
sBarterValueMultiplier = Barter Mode Multiplier 
sSpendItemsBeforeGold = Spend Items Before Gold
sCursedGoldMode = Cursed Gold Mode
sIncludePowerModifiers = Include Price Power Modifiers
sIncludePerkModifiers = Include Price Perk Modifiers
sBlockFollowerInjection = Block Follower Gold Injection
sUseActivateHandler = Early Gold Injection on Activate


; Tab 2
sColorsHeader = Pick your notification colors.
sColorStatusActive = Active Status
sColorStatusInactive = Inactive Status
sColorGoldAsset = Gold Asset
sColorLootAsset = Item Asset
sColorTotalAsset = Total Asset
sColorExpectedValue = Expected Value
sColorSystemHeader = System Header
sItemNotificationMode = Traded item Notification Mode
sItemNotificationMode0 = Default
sItemNotificationMode1 = Truncated
sItemNotificationMode2 = Message Box
sItemNotificationMode3 = Console
sShowModeStatus = Display Modes info line
sShowExpectedValue = Display Expected Value line
sEnableDebug = Enable Debug Notifications

; Tab 3
sLabelsHeader = Edit labels used by the mod.
sCurrencyName = Currency Name
sLabelGold = Gold Label
sLabelGoldAbbr = Gold Abbreviation
sLabelOn = ON Label
sLabelOff = OFF Label
sLabelActive = ACTIVE Label
sLabelInactive = INACTIVE Label
sLabelModeFixed = Fixed Mode Label
sLabelModeCurrency = Currency Mode Label
sLabelModeBarter = Barter Mode Label

; Extras
sUnsavedPending = * Unsaved Changes Pending
sBtnApply   = Save and Apply Settings
sBtnDiscard = Discard Unsaved Changes
sBtnRestore = Restore Backup Settings
sConfirmRestore = Restore active tab entries?
sBtnYesRestore = Yes, Restore
sBtnCancel = Cancel
sSavedSuccess = Settings applied and saved!