[Settings]
; {HOTKEYS & MOD STARTUP STATE}
bEnabled   = true
uToggleKey = 13
uWealthKey = 34

; {ECONOMY & GAMEPLAY SETTINGS}
iItemValueMode 		= 0
iSpendingOrderMode 	= 0
fBarterModeMultiplier   = 1.0
bSpendItemsBeforeGold   = true
bCursedGoldMode         = false
bIncludePowerModifiers  = true
bIncludePerkModifiers   = true
bBlockFollowerInjection	= true
bEarlyGoldInjection 	= true
sGoldFormID 		= 0x0000000F

; {ASSET & CURRENCY NAMES}
sCurrencyName   = Loot
sLabelGold      = Gold
sLabelGoldAbbr  = g

; {COLORS AND NOTIFICATION DISPLAY CUSTOMIZATION}
sColorStatusActive   = 00FF00
sColorStatusInactive = FF3333
sColorGoldAsset      = FFD700
sColorLootAsset      = 00BFFF
sColorTotalAsset     = 00FF00
sColorExpectedValue  = FF8C00
sColorSystemHeader   = A9A9A9

iItemNotificationMode = 0

bShowModeStatus    = true
bShowExpectedValue = false
bEnableDebugNotifications = false

[Messages]
sMsgCursedGold          = <font color='#{}'>Cursed </font><font color='#{}'>{}</font><font color='#{}'> burns your flesh!</font>
sMsgTradedPerItem       = <font color='#{}'>Traded {}x </font><font color='#{}'>{}</font>
sMsgTruncatedHeader     = <font color='#{}'>Traded: </font>{}
sMsgTruncatedMore       =  <font color='#{}'>and {} more...</font>
sMsgMsgBoxHeader        = {} Traded 
sMsgMsgBoxLimiter       = _______________________________
sMsgMsgBoxTruncated     = ...and {} more types of {}.
sMsgTradingStatusMsg    = <font color='#{}'>Cannot revalue your </font><font color='#{}'>{}</font><font color='#{}'> stash while occupied.</font>
sMsgTradingStatusToggle = <font color='#{}'>{}</font><font color='#{}'> Trading: </font>{}
sMsgAssetSummary        = <font color='#{}'>{}: {}</font> <font color='#{}'>|</font> <font color='#{}'>{}: {}</font> <font color='#{}'>|</font> <font color='#{}'>Total: {}</font>
sMsgExpectedValue       = <font color='#{}'>Expected {} Value: {}%</font>
sMsgFrameworkStatus     = <font color='#{}'>{} Trading: {} </font><font color='#{}'>| Mode: {}, </font><font color='#{}'>{}</font><font color='#{}'> 1st | Speech {}</font>
sMsgChangeReceived      = <font color='#{}'>Change Received: </font><font color='#{}'>{}{}</font><font color='#{}'>. Wasted </font><font color='#{}'>{}{}</font>.
sMsgNoChange            = <font color='#{}'>No Change Received. Wasted </font><font color='#{}'>{}{}</font>.

sLabelOn                = ON
sLabelOff               = OFF	
sLabelActive            = ACTIVE
sLabelInactive          = INACTIVE
sLabelModeCurrency      = Currency
sLabelModeBarter        = Barter
sLabelModeFixed         = Fixed